### PR TITLE
Add a simple style manager for better maintainability of styling

### PR DESCRIPTION
**Pull request by jayvesmir**
creating a styleManager class that has some basic functionality for keeping track of styles across the app

### CODE REVIEW

**Comment by jayvesmir** [comment]
Linked to issue [#4](https://github.com/Wolfmyths/Genshin-Stopwatch/issues/4)

**Comment by Wolfmyths** [comment]
I like this idea, but when I run the code not everything is stylized correctly. I'm not sure if I am running the code incorrectly but this was happening to me ever since I started stylizing the program, which is why the stylesheets are placed how they are now.

image

The stopwatch frames aren't the correct color, when the reset timer button is clicked the color doesn't change, etc. I'm not totally sure why this happens.

**Comment by Wolfmyths** [comment]
I did some digging and I believe the answer is in this documentation here for [PyQt5's Stylesheet Syntax](https://doc.qt.io/qt-5/stylesheet-syntax.html) I'll have to look more into this.

I also found out from this we can use your `global styles` and just apply it to the `qtw.QApplication` object and use that

Update: I was messing around and turns out it was a cascading issue. I was able to put almost all style elements into one sheet. Before I can merge I want to fix this on your fork. I can make a branch to show you a version of main.py with everything more organized with less duplicate stylesheets.

**Comment by jayvesmir** [comment]
It would be great if you show me what you mean, but as I understand, you've fixed the issue. That's good to hear and I would appreciate you create a branch for it like you said so I can add it to my PR! <3

**Comment by Wolfmyths** [comment]
[styleSheet Branch](https://github.com/Wolfmyths/Genshin-Stopwatch/tree/styleSheet-Rewrite)
Yeah I think I have fixed my issue for the most part, but I like your idea in keeping the stylesheets in a separate script. I feel like it would make the code a lot easier to navigate in. I think with the structure of the styleManager class you made we can put the updated stylesheets in there and organize them a little better by defining parts of the big stylesheet to variables like how you already have them. And then we can make a method to change the color palette. If you still want to help out you can do that.

**Comment by Wolfmyths** [comment]
@jayvesmir Can you update your PR to match with the new [stylesheet rework branch](https://github.com/Wolfmyths/Genshin-Stopwatch/tree/styleSheet-Rewrite)? I want to credit you!

**Comment by jayvesmir** [comment]
I'm so sorry, I missed a few days on here lol, I'll update it now

**Comment by jayvesmir** [comment]
I'm not able to look at the code right now so I'm entrusting everything upon you hehe

**Comment by jayvesmir** [comment]
I've now also merged main into the styleSheet-Rewrite branch on my fork, but there are some functionality issues that I'm experiencing. I don't know if this is my fault but I cannot look into it right now. 

***Please don't merge the PR yet***

For some reason I thought this would be a great idea...

**Comment by Wolfmyths** [comment]
Yeah I just did a test run and I noticed some issues too, I'll look into it and if I find out the issue I'll just merge and fix it myself

**Comment by Wolfmyths** [comment]
I'm not really sure what went wrong with your build because the system tray icon won't even show up, I'm rewriting your code but I'll still merge to make you a contributor when I finish.

One thing I noticed in your `style.py` is that your attributes weren't defined in the class which might have been the reason why some things weren't applying correctly. My version defined the stylesheet strings before `def __init__()` and they seem to be working.

In python when you import a file it will run the code which is why `if __name__ =='__main__':` is used so much. So I think your attributes turned into something similar to a global variable to the program. Putting attributes in a function or class prevents this also.

I've been struggling with PyQt5 stylesheets on every project that uses this framework so don't worry about it.

Correction: to use those attributes you need to put it in `__init__()` so you can call it later with `self`, nooby mistake ;-;

**Comment by jayvesmir** [comment]
Sorry for causing the trouble, thank you for merging anyway. I've never really used python on this of a level so thanks for the opportunity too :)

**Pull request merged**
